### ISSUE TITLE
Components are exported twice

### ISSUE THREAD

**Issue by aloifolia** [chrisvxd/story2sketch#49]
Whenever I import the generated `stores.asketch.json` into Sketch, every component is listed twice.

For example, the following code

```ts
storiesOf("Stuff", module).add("Button", () => (
  <button style={{ backgroundColor: "red", borderRadius: "4px" }}>
    you have to click me now
  </button>
));
```

yields the following result: 
<img width="1156" alt="screen shot 2018-11-23 at 14 03 45" src="https://user-images.githubusercontent.com/1295054/48944885-ac1b4a00-ef28-11e8-823c-d284332dd748.png">

Also, the container around the button is drawn too small and there should be no line break. Any idea, what might cause this issue?

**Comment by chrisvxd** [comment]
Hey @aloifolia! That's because you're using the default `viewports` functionality - the one on the left is mobile, the one on the right is desktop, as denoted by the little 📱 and 🖥 . You can update your `storybook.config.js` file to configure this and set one viewport, if you need:

```
  viewports: {
    standard: {
      width: 1920,
      height: 1200,
      symbolPrefix: "Desktop/"
    }
  }
```

Regarding the button, can you show me a screenshot of what it _should_ look like please?

**Comment by chrisvxd** [comment]
Closing
